/**
 * Supported Languages List
 * Client-side safe - no Redis or server dependencies
 */

export const SUPPORTED_LANGUAGES = {
  // Major languages (Tier 1)
  'en': 'English',
  'ko': '한국어',
  'ja': '日本語',
  'zh-CN': '简体中文',
  'zh-TW': '繁體中文',
  'es': 'Español',
  'fr': 'Français',
  'de': 'Deutsch',
  'ru': 'Русский',
  'pt': 'Português',
  'pt-BR': 'Português (Brasil)',
  'it': 'Italiano',
  'ar': 'العربية',
  'hi': 'हिन्दी',
  'bn': 'বাংলা',
  'pa': 'ਪੰਜਾਬੀ',
  'jv': 'Basa Jawa',
  'vi': 'Tiếng Việt',
  'mr': 'मराठी',
  'ta': 'தமிழ்',
  'gu': 'ગુજરાતી',
  'kn': 'ಕನ್ನಡ',
  'te': 'తెలుగు',
  'ur': 'اردو',
  'th': 'ไทย',
  'id': 'Bahasa Indonesia',
  'ms': 'Bahasa Melayu',
  'tl': 'Tagalog',
  'pl': 'Polski',
  'uk': 'Українська',
  'cs': 'Čeština',
  'hu': 'Magyar',
  'ro': 'Română',
  'el': 'Ελληνικά',
  'tr': 'Türkçe',
  'bg': 'Български',
  'hr': 'Hrvatski',
  'sk': 'Slovenčina',
  'sl': 'Slovenščina',
  'et': 'Eesti keel',
  'lt': 'Lietuvių kalba',
  'lv': 'Latviešu valoda',
  'sw': 'Kiswahili',
  'so': 'Soomaali',
  'rw': 'Kinyarwanda',
  'ny': 'Chichewa',
  'mg': 'Malagasy',
  'mt': 'Maltese',
  'is': 'Íslenska',
  'ga': 'Gaeilge',
  'cy': 'Cymraeg',
  'sq': 'Shqiptare',
  'mk': 'Македонски',
  'ka': 'ქართული',
  'hy': 'Հայերեն',
  'az': 'Azərbaycanca',
  'kk': 'Қазақ',
  'uz': 'Ўзбек',
  'ky': 'Кыргызча',
  'tg': 'Тоҷикӣ',
};
