export default {
  name: 'board',
  title: 'Board',
  type: 'document',
  fields: [
    {
      name: 'name',
      title: 'Board Name',
      type: 'string',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'name',
        maxLength: 96,
      },
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'description',
      title: 'Description',
      type: 'text',
    },
    {
      name: 'type',
      title: 'Board Type',
      type: 'string',
      options: {
        list: [
          { title: 'Free Board (자유게시판)', value: 'free' },
          { title: 'Anonymous Board (익명게시판)', value: 'anonymous' },
          { title: 'Topic Board (주제별)', value: 'topic' },
          { title: 'Notice Board (공지사항)', value: 'notice' },
          { title: 'Best Board (베스트)', value: 'best' },
          { title: 'Gallery (갤러리)', value: 'gallery' },
        ],
        layout: 'radio',
      },
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'category',
      title: 'Category',
      type: 'reference',
      to: [{ type: 'category' }],
    },
    {
      name: 'isAnonymous',
      title: 'Allow Anonymous Posts',
      type: 'boolean',
      initialValue: false,
    },
    {
      name: 'requireApproval',
      title: 'Require Post Approval',
      type: 'boolean',
      initialValue: false,
    },
    {
      name: 'moderators',
      title: 'Moderators',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'user' }] }],
    },
    {
      name: 'rules',
      title: 'Board Rules',
      type: 'array',
      of: [{ type: 'block' }],
    },
    {
      name: 'icon',
      title: 'Icon',
      type: 'string',
      description: 'Icon name or emoji',
    },
    {
      name: 'color',
      title: 'Theme Color',
      type: 'string',
      description: 'Hex color code',
    },
    {
      name: 'isActive',
      title: 'Is Active',
      type: 'boolean',
      initialValue: true,
    },
    {
      name: 'order',
      title: 'Display Order',
      type: 'number',
      initialValue: 0,
    },
    {
      name: 'postCount',
      title: 'Total Posts',
      type: 'number',
      readOnly: true,
      initialValue: 0,
    },
    {
      name: 'subscriberCount',
      title: 'Subscribers',
      type: 'number',
      readOnly: true,
      initialValue: 0,
    },
  ],
  preview: {
    select: {
      title: 'name',
      subtitle: 'type',
      icon: 'icon',
    },
  },
};
